1) Remove dependency on rubygems and json, so it's more independent, and can run when no gem is even installed at all.
2) BAD: Add some options and cache capacity to VersionedGem#download without specs.

3) WARN: This is a buggy version committed before partial refactor. It's not handling semantic version comparison correctly.

details:

If one run `ruby -r'./versioned_gem' -e "VersionedGem.new('rails', '3.0.10').download(:recursive => true, :install => true)"`, it will report the following error finally:

 Installing rails-3.0.10.gem...
ERROR:  While executing gem ... (Gem::DependencyError)
    Unable to resolve dependencies: actionmailer requires mail (~> 2.2.19); activerecord requires arel (~> 2.0.10), tzinfo (~> 0.3.23); actionpack requires i18n (~> 0.5.0), rack-mount (~> 0.6.14), tzinfo (~> 0.3.23); activemodel requires i18n (~> 0.5.0)

4) Remove garbage attempted code in gem_installer.rb and rename it to blah.rb for the time being.